stages:
    - deploy

variables:
  DEPLOY_PATH: /var/docker/services

before_script:
  - echo "ENV=production" >> .env
  - echo "VAR_ROOT=/var" >> .env
  - echo "COMPOSE_PROJECT_NAME=gpcentre" >> .env

deploy:services:
  stage: deploy
  # variables:
  #   CI_DEBUG_TRACE: "true"
  script:
    - rm -rf "$DEPLOY_PATH"
    - cp -R "$CI_PROJECT_DIR" "$DEPLOY_PATH"
    - cd "$DEPLOY_PATH"
    - docker-compose up -d
    - rm -rf .git*

