stages:
    - deploy

deploy_prod:
  stage: deploy
  script:
    - rm -rf /var/docker/vhosts
    - mv $CI_PROJECT_DIR /var/docker/vhosts
    - cd /var/docker/vhosts
    - docker-compose down && docker-compose build && docker-compose up
  environment:
    name: production
    url: https://www.gpcentre.net/
  only:
  - master
