stages:
    - deploy

deploy_prod:
  stage: deploy
  script:
    - rm -rf /var/docker/gpcentre-base
    - mkdir /var/docker/gpcentre-base
    - echo "Directory: $CI_PROJECT_DIR"
    - cp -R $CI_PROJECT_DIR/* /var/docker/gpcentre-base
    - cd /var/docker/gpcentre-base
    - rm -rf .git*
    - echo "ENV=production" >> .env
    - echo "VAR_ROOT=/var" >> .env
    - docker-compose down && docker-compose up -d
  environment:
    name: production
    url: https://www.gpcentre.net/
  only:
  - master
