stages:
    - deploy

variables:
  DEPLOY_PATH: /var/docker/services
#  CI_DEBUG_TRACE: "true"

before_script:
  - echo APPLICATION_ENV=production > .env
  - echo COMPOSE_PROJECT_NAME=gpcentre >> .env
  - echo NGINX_FILES_PATH=$DEPLOY_PATH/nginx >> .env

deploy:services:
  stage: deploy
  script:
    - docker-compose up -d --remove-orphans
