version: '3'
services:
  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    depends_on:
      - nginx
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    depends_on:
      - nginx
      - nginx-gen
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  # Success! Discovered from: https://gist.github.com/lucidfrontier45/497341c4b848dfbd6dfb
  mariadb-node1:
    image: hauptmedia/mariadb:10.1
    hostname: mariadb-node1
    ports:
      - 13306:3306
    restart: unless-stopped
    environment:
      - TIMEZONE=America/Los_Angeles
      - MYSQL_ROOT_PASSWORD=password
      - REPLICATION_PASSWORD=repli
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=test
      - GALERA=On
      - NODE_NAME=mariadb-node1
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://
    command: --wsrep-new-cluster
    volumes:
      - "$VAR_ROOT/lib/mysql-node1:/var/lib/mysql"
  mariadb-node2:
    image: hauptmedia/mariadb:10.1
    hostname: mariadb-node2
    restart: unless-stopped
    links:
      - mariadb-node1
    ports:
      - 23306:3306
    environment:
      - TIMEZONE=America/Los_Angeles
      - REPLICATION_PASSWORD=repli
      - GALERA=On
      - NODE_NAME=node2
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://mariadb-node1
    volumes:
      - "$VAR_ROOT/lib/mysql-node2:/var/lib/mysql"
  mariadb-node3:
    image: hauptmedia/mariadb:10.1
    hostname: mariadb-node3
    restart: unless-stopped
    links:
      - mariadb-node1
    ports:
      - 33306:3306
    environment:
      - TIMEZONE=America/Los_Angeles
      - REPLICATION_PASSWORD=repli
      - GALERA=On
      - NODE_NAME=node3
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://mariadb-node1
    volumes:
      - "$VAR_ROOT/lib/mysql-node3:/var/lib/mysql"
