version: '2'
services:
  vhosts:
    #build: ./vhosts
    image: nginx:latest
    container_name: vhosts
    environment:
      WORKDIR: /etc/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
       - php71:phpfcgi
    volumes:
      - ./var/www:/var/www
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./var/lib/php-fpm:/var/lib/php-fpm
  php71:
    #build: ./php71
    image: php:fpm
    container_name: php71
    environment:
      WORKDIR: /usr/local/etc
    ports:
      - "9000:9000"
#    links:
#      - mysql:gpc.database
    volumes:
      - ./etc/php-fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./etc/php-fpm/conf.d/zz-docker.ini:/usr/local/etc/php/conf.d/zz-docker.ini
      - ./var/www:/var/www
      - ./var/lib/php-fpm:/var/lib/php-fpm
  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   volumes:
  #     - ./data/lib/mysql:/var/lib/mysql
  #     - ./data/config/mysql/conf.d:/etc/mysql/conf.d
  #     - ./data/config/mysql/init.db:/docker-entrypoint-initdb.d
