version: '2'
services:
  proxy: 
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
  php71:
    image: php:fpm
    container_name: php71
    volumes:
      - ./etc/php-fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./etc/php-fpm/conf.d/zz-docker.ini:/usr/local/etc/php/conf.d/zz-docker.ini
      - "$VAR_ROOT/www:/var/www"
      - "$VAR_ROOT/lib/php-fpm:/var/lib/php-fpm"
  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   volumes:
  #     - ./var/lib/mysql:/var/lib/mysql
  #     - ./etc/mysql/conf.d:/etc/mysql/conf.d
  #     - ./etc/mysql/init.db:/docker-entrypoint-initdb.d